version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mariadb
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www
    networks:
      - inception-network

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge

volumes:
  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress